prSections:
  - title: My Pull Requests
    filters: is:open author:@me
  - title: Needs My Review
    filters: is:open review-requested:@me
  - title: Involved
    filters: is:open involves:@me -author:@me

issuesSections:
  - title: My Issues
    filters: is:open author:@me
  - title: Assigned
    filters: is:open assignee:@me
  - title: Involved
    filters: is:open involves:@me -author:@me

notificationsSections:
  - title: All
    filters: ""
  - title: Participating
    filters: reason:participating
  - title: Mentioned
    filters: reason:mention
  - title: Review Requested
    filters: reason:review-requested

repoPaths:
  lasseh/*: ~/code/go/src/github.com/lasseh/*
  yolo-as/network-config: ~/code/go/src/github.com/lasseh/yolo/network-config

defaults:
  view: prs
  preview:
    open: true
    width: 100
  refetchIntervalMinutes: 30
  prsLimit: 20
  issuesLimit: 20

theme:
  ui:
    sectionsShowCount: true
    table:
      compact: false
  colors:
    text:
      primary: "#c0caf5"
      secondary: "#a9b1d6"
      inverted: "#1a1b26"
      faint: "#565f89"
      warning: "#e0af68"
      success: "#9ece6a"
    background:
      selected: "#283457"
    border:
      primary: "#27a1b9"
      secondary: "#565f89"
      faint: "#414868"

keybindings:
  prs:
    - key: c
      command: >
        tmux new-window -c {{.RepoPath}} '
        gh pr create --web --repo {{.RepoName}}
        '
    - key: O
      builtin: checkout
  issues:
    - key: c
      command: >
        tmux new-window -c {{.RepoPath}} '
        gh issue create --web --repo {{.RepoName}}
        '

pager:
  diff: delta
